site_dc:
  hosts:
    dc_dist_1:
      ansible_host: 192.168.199.1
      interfaces:
        - name: TenGigabitEthernet1/0/48
          description: "**DC-FW**"
          mode: layer3
          address:
            v4: 10.0.200.2/30
            v6: LLA
        - name: TenGigabitEthernet1/1/1
          description: "**DC-DIST-2**"
          mode: layer3
        - name: TenGigabitEthernet1/1/2
          description: "**DC-DIST-2**"
          mode: layer3
        - name: TenGigabitEthernet1/0/37
          description: "**DC-ACC-1**"
          mode: layer2
          sw_mode: trunk
          allowed_vlans: 10,199
        - name: TenGigabitEthernet1/0/38
          description: "**DC-ACC-2**"
          mode: layer2
          sw_mode: trunk
          allowed_vlans: 20,199
        - name: TenGigabitEthernet1/0/39
          description: "**DC-ACC-3**"
          mode: layer2
          sw_mode: trunk
          allowed_vlans: 199
        - name: Port-channel1
          description: "**DC-DIST-2**"
          mode: layer3
          address:
            v4: 10.0.201.1/30
            v6: LLA
        - name: Loopback0
          address:
            v4: 10.0.222.1/32
            v6: 2a14:7001:1111:1141::1/64
        - name: Vlan10
          address:
            v4: 10.0.10.4/29
            v6: 2a14:7001:2648:2648::def1/64
        - name: Vlan20
          address:
            v4: 10.0.20.252/24
            v6: 2a14:7000:9999:9999::def1/64
        - name: Vlan199
          address:
            v4: 10.0.199.252/24
            v6: 2a14:7000:0:199::def1/64
      ospf_routerid: 0.3.1.1

    dc_dist_2:
      ansible_host: 192.168.199.2
      interfaces:
        - name: TenGigabitEthernet1/0/48
          description: "**DC-FW**"
          mode: layer3
          address:
            v4: 10.0.200.6/30
            v6: LLA
        - name: TenGigabitEthernet1/1/1
          description: "**DC-DIST-1**"
          mode: layer3
        - name: TenGigabitEthernet1/1/2
          description: "**DC-DIST-1**"
          mode: layer3
        - name: TenGigabitEthernet1/0/37
          description: "**DC-ACC-1**"
          mode: layer2
          sw_mode: trunk
          allowed_vlans: 10,199
        - name: TenGigabitEthernet1/0/38
          description: "**DC-ACC-2**"
          mode: layer2
          sw_mode: trunk
          allowed_vlans: 20,199
        - name: TenGigabitEthernet1/0/39
          description: "**DC-ACC-3**"
          mode: layer2
          sw_mode: trunk
          allowed_vlans: 199
        - name: Port-channel1
          description: "**DC-DIST-1**"
          mode: layer3
          address:
            v4: 10.0.201.2/30
            v6: LLA
        - name: Loopback0
          address:
            v4: 10.0.222.2/32
            v6: 2a14:7001:1111:1142::2/64
        - name: Vlan10
          address:
            v4: 10.0.10.5/29
            v6: 2a14:7001:2648:2648::def2/64
        - name: Vlan20
          address:
            v4: 10.0.20.253/24
            v6: 2a14:7000:9999:9999::def2/64
        - name: Vlan199
          address:
            v4: 10.0.199.253/24
            v6: 2a14:7000:0:199::def2/64
      ospf_routerid: 0.3.2.2
  vars:
    vlans:
      - name: Private
        id: 10
      - name: ASA
        id: 20
      - name: Management
        id: 199
    routing:
      v4: true
      v6: true
      ospf_pid: 1
      ospf_area: 0

site_office:
  hosts:
    office_dist_1:
      ansible_host: 192.168.199.3
      ospf_routerid: 1.3.1.1
      interfaces:
        - name: TenGigabitEthernet1/0/37
          description: "**OFFICE-ACC-1**"
          mode: layer2
          sw_mode: trunk
          allowed_vlans: 110,120,130,199

        - name: TenGigabitEthernet1/0/38
          description: "**OFFICE-ACC-2**"
          mode: layer2
          sw_mode: trunk
          allowed_vlans: 110,120,130,199

        - name: TenGigabitEthernet1/0/39
          description: "**OFFICE-ACC-3**"
          mode: layer2
          sw_mode: trunk
          allowed_vlans: 110,120,130,199

        - name: TenGigabitEthernet1/0/40
          description: "**OFFICE-FW**"
          mode: layer3
          address:
            v4: 10.1.201.10/30
            v6: LLA

        - name: TenGigabitEthernet1/0/45
          description: "**OFFICE-DIST-2**"
          mode: layer3
        - name: TenGigabitEthernet1/0/46
          description: "**OFFICE-DIST-2**"
          mode: layer3
        - name: TenGigabitEthernet1/0/47
          description: "**OFFICE-DIST-2**"
          mode: layer3
        - name: TenGigabitEthernet1/0/48
          description: "**OFFICE-DIST-2**"
          mode: layer3
        - name: Port-channel1
          description: "**OFFICE-DIST-2**"
          mode: layer3
          address:
            v4: 10.1.200.1/30
            v6: LLA
        - name: GigabitEthernet1/0/36
          description: "**OFFICE-SRV**"
          mode: layer3
          address:
            v4: 10.1.10.2/30
            v6: 2A09:F8C0:1:1::DEF/64

        - name: Vlan110
          address:
            v4: 10.1.110.231/24
            v6: 2A09:F8C0:1:110::11/64
        - name: Vlan120
          address:
            v4: 10.1.120.231/24
            v6: 2A09:F8C0:1:120::11/64
        - name: Vlan130
          address:
            v4: 10.1.130.231/24
            v6: 2A09:F8C0:1:130::11/64
        - name: Vlan199
          address:
            v4: 10.1.199.231/24
            v6: 2A09:F8C0:1:199::11/64

      
    office_dist_2:
      ansible_host: 192.168.199.4
      ospf_routerid: 1.3.2.2
      interfaces:
        - name: TenGigabitEthernet1/0/37
          description: "**OFFICE-ACC-1**"
          mode: layer2
          sw_mode: trunk
          allowed_vlans: 110,120,130,199

        - name: TenGigabitEthernet1/0/38
          description: "**OFFICE-ACC-2**"
          mode: layer2
          sw_mode: trunk
          allowed_vlans: 110,120,130,199

        - name: TenGigabitEthernet1/0/39
          description: "**OFFICE-ACC-3**"
          mode: layer2
          sw_mode: trunk
          allowed_vlans: 110,120,130,199

        - name: TenGigabitEthernet1/0/40
          description: "**OFFICE-FW**"
          mode: layer3
          address:
            v4: 10.1.201.14/30
            v6: LLA

        - name: TenGigabitEthernet1/0/45
          description: "**OFFICE-DIST-1**"
          mode: layer3
        - name: TenGigabitEthernet1/0/46
          description: "**OFFICE-DIST-1**"
          mode: layer3
        - name: TenGigabitEthernet1/0/47
          description: "**OFFICE-DIST-1**"
          mode: layer3
        - name: TenGigabitEthernet1/0/48
          description: "**OFFICE-DIST-1**"
          mode: layer3
        - name: Port-channel1
          description: "**OFFICE-DIST-1**"
          mode: layer3
          address:
            v4: 10.1.200.2/30
            v6: LLA

        - name: TenGigabitEthernet1/1/1
          description: "**OFFICE-WLC**"
          mode: layer2
          sw_mode: trunk
          allowed_vlans: 210,220
        - name: TenGigabitEthernet1/1/2
          description: "**OFFICE-WLC**"
          mode: layer2
          sw_mode: trunk
          allowed_vlans: 210,220

        - name: Port-channel2
          description: "**OFFICE-WLC**"
          mode: layer2
          sw_mode: trunk
          allowed_vlans: 210,220

        - name: Vlan110
          address:
            v4: 10.1.110.232/24
            v6: 2A09:F8C0:1:110::12/64
        - name: Vlan120
          address:
            v4: 10.1.120.232/24
            v6: 2A09:F8C0:1:120::12/64
        - name: Vlan130
          address:
            v4: 10.1.130.232/24
            v6: 2A09:F8C0:1:130::12/64
        - name: Vlan199
          address:
            v4: 10.1.199.232/24
            v6: 2A09:F8C0:1:199::12/64
        - name: Vlan210
          address:
            v4: 10.1.210.232/24
            v6: 2A09:F8C0:1:210::12/64
        - name: Vlan220
          address:
            v4: 10.1.220.232/24
            v6: 2A09:F8C0:1:220::12/64

  vars:
    vlans:
      - name: Marketing
        id: 110
      - name: Accounting
        id: 120
      - name: HR
        id: 130
      - name: Corporate-WIFI
        id: 210
      - name: Guest-WIFI
        id: 220
      - name: Management
        id: 199
    routing:
      v4: true
      v6: true
      ospf_pid: 1
      ospf_area: 100

site_station:
  hosts:
    station_dist:
      ansible_host: 192.168.199.5
      ospf_routerid: 2.2.1.1
      interfaces:
        - name: GigabitEthernet1/0/1
          description: "**STATION**"
          mode: layer3
          address:
            v4: 10.101.200.2/30
            v6: LLA
        - name: GigabitEthernet1/0/2
          description: "**STATION-ACC-1**"
          mode: layer2
          sw_mode: trunk
          allowed_vlans: 10,199
        - name: GigabitEthernet1/0/3
          description: "**STATION-ACC-2**"
          mode: layer2
          sw_mode: trunk
          allowed_vlans: 10,199
        - name: GigabitEthernet1/0/4
          description: "**STATION-PRIVATE**"
          mode: layer2
          sw_mode: access
          vlan_id: 10
        - name: Vlan10
          address:
            v4: 10.101.10.254/24
            v6: 2a0b:fac0:101:10::def/64
        - name: Vlan199
          address:
            v4: 10.101.199.254/24
            v6: 2a0b:fac0:101:199::def/64
  vars:
    vlans:
      - name: Users
        id: 10
      - name: Management
        id: 199
    routing:
      v4: true
      v6: true
      ospf_pid: 1
      ospf_area: 100

ios_devices:
  children:
    site_dc:
    site_office:
    site_station:

all_devices:
  children:
    site_dc:
    site_office:
    site_station:
  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
    ansible_user: ansible
    ansible_password: pM6uhrkEn24LCb244E7K
